apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T12:20:39Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4127"
  uid: 50888b39-6ead-4da3-b0fd-252554a2a1fc
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.97.35.12
  clusterIPs:
  - 10.97.35.12
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31655
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
